Added macOS Build instructions
yuzu-mirror/yuzu pull request #13
Opened 2024-03-05 22:12 UTC by paypay-a

Added macOS Build instruction link back onto the readme

2024-03-05 22:15 UTC, paypay-a commented
the workflow shouldnt affect anything since it doesn't exist anymore :)

2024-03-05 22:18 UTC, paypay-a commented
i also have made some changes to the wiki on my repo if you wanna try and reflect those on this one

2024-03-06 01:04 UTC, ascpixi requested changes
Thanks for the PR! I guess since the README was already modified, there's not much change to the parity of the repo, so we can get this through.

2024-03-06 01:04 UTC, ascpixi commented on README.md
> +* ## Download
Why was this header made a list entry?

2024-03-06 02:07 UTC, paypay-a commented on README.md
> +* ## Download
Complete accident

2024-03-06 02:08 UTC, paypay-a commented
Fixed the header being a list entry. Was a mistake i didnt catch before commiting it

2024-03-06 02:10 UTC, ascpixi commented
Seems good, thank you!

2024-03-06 02:10 UTC, merged